on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello message
        run: echo "Hello"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Builds dotnet project
        run: dotnet build ActionsKataExample
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Runs tests for dotnet project
        run: dotnet test ActionsKataExample
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publishes dotnet project
        run: dotnet publish ActionsKataExample
